# Generated by Django 4.2.2 on 2023-07-04 08:49

from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='failed_frame1',
            field=models.ImageField(blank=True, upload_to=repository.models.client_failed_directory_path),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failed_frame2',
            field=models.ImageField(blank=True, upload_to=repository.models.client_failed_directory_path),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failed_frame3',
            field=models.ImageField(blank=True, upload_to=repository.models.client_failed_directory_path),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failed_frame4',
            field=models.ImageField(blank=True, upload_to=repository.models.client_failed_directory_path),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failed_frame5',
            field=models.ImageField(blank=True, upload_to=repository.models.client_failed_directory_path),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
