# Generated by Django 4.2.2 on 2023-07-13 10:17

from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_loginattempt_failed_frame1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default=None, upload_to=repository.models.content_directory_path),
        ),
    ]
