# Generated by Django 4.2.2 on 2023-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_remove_content_file_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='suggestion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
