# Generated by Django 4.2.2 on 2023-08-31 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0005_client_user_directory_admin_credentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(max_length=100)),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.directory')),
            ],
        ),
    ]
